baseurl      = "mateidavid.github.io"
title        = "matei's blog(wip)"
languageCode = "en-us"
theme        = "hello-friend-ng"
paginate     = 10

PygmentsCodeFences = true
PygmentsStyle = "monokai"
copyright = "This work is licensed under a Creative Commons Attribution-NonCommercial 4.0 International License." # This message is only used by the RSS template.

#googleAnalytics = ""
# disqusShortname""

archetypeDir = "archetypes"
contentDir   = "content"
dataDir      = "data"
layoutDir    = "layouts"
publishDir   = "public"


buildDrafts  = false
buildFuture  = false
buildExpired = false
canonifyURLs = true

enableRobotsTXT = true
enableGitInfo   = false
enableEmoji     = true
enableMissingTranslationPlaceholders = false
disableRSS     = false
disableSitemap = false
disable404     = false
disableHugoGeneratorInject = false

[permalinks]
  posts = "/posts/:year/:month/:title/"

[author]
  name = "Matei David"


[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04 -0700"

  # Subtitle for home
  homeSubtitle = "A collection of awfully average tech write ups"

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = false

  # Enable sharing buttons, if you linke
  enableSharingButtons = true

  # Metadata mostly used in document's head
  description = "My new homepage or blog"
  keywords = "homepage, blog"
  images = [""]

  # Default theme "light" or "dark"
  defaultTheme = "dark"

[taxonomies]
    category = "blog"
    tag      = "tags"
    series   = "series"

  [[params.social]]
    name = "twitter"
    url  = "https://twitter.com/__mateidavid"

  [[params.social]]
    name = "github"
    url  = "https://github.com/matei207"

  [[params.social]]
    name = "linkedin"
    url  = "https://www.linkedin.com/in/mateidavid"

  [[params.social]]
    name = "stackoverflow"
    url  = "https://stackoverflow.com/users/7070273/wink207"

  [[params.social]]
    name = "dev"
    url = "https://dev.to/__mateidavid"
[languages]
  [languages.en]
    title = "Matei David's WIP blog"
    subtitle = "A simple theme for Hugo"
    keywords = ""
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "init matei.codes()"
      logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

  # And you can even create generic menu
  [menu]
    [[menu.main]]
    identifier = "about"
    name       = "About"
    url        = "about/"
  [[menu.main]]
    identifier = "posts"
    name       = "Posts"
    url        = "posts/"
